version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "13:00"
      timezone: Europe/Brussels
    open-pull-requests-limit: 99
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "11:00"
      timezone: Europe/Brussels
    open-pull-requests-limit: 99
